# Setup
title:        naotoizu_7010
tagline:      Hello World!
baseurl:      ""
paginate:     1
locale:       "jp"

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown